# Generated by Django 4.0.5 on 2022-07-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamsCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.FloatField(default=0.0, verbose_name='Стоимость врезки, руб')),
                ('path', models.FloatField(default=0.0, verbose_name='Стоимость 1м пробега, руб')),
            ],
            options={
                'verbose_name': 'Стоимостные параметры',
                'verbose_name_plural': 'Стоимостные параметры',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина, мм')),
                ('height', models.IntegerField(default=0, verbose_name='Высота, мм')),
                ('cost', models.FloatField(default=0.0, verbose_name='Стоимость листа, руб')),
            ],
            options={
                'verbose_name': 'лист',
                'verbose_name_plural': 'листы',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizont_size', models.IntegerField(default=0, verbose_name='Поля слева и справа, мм')),
                ('vertical_size', models.IntegerField(default=0, verbose_name='Поля сверху и снизу, мм')),
            ],
            options={
                'verbose_name': 'технологическое поле',
                'verbose_name_plural': 'технологические поля',
            },
        ),
    ]
