# Generated by Django 4.0.5 on 2022-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf_calc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParamsCost',
        ),
        migrations.AddField(
            model_name='sheet',
            name='entry',
            field=models.FloatField(default=0.0, verbose_name='Стоимость врезки, руб'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='path',
            field=models.FloatField(default=0.0, verbose_name='Стоимость 1м пробега, руб'),
        ),
    ]
