# Generated by Django 4.0.5 on 2022-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf_calc', '0002_delete_paramscost_sheet_entry_sheet_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='material',
            field=models.CharField(default='Металл', max_length=30, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='thickness',
            field=models.IntegerField(default=1, verbose_name='Толщина, мм'),
        ),
    ]
