# Generated by Django 4.0.5 on 2022-07-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf_calc', '0003_sheet_material_sheet_thickness'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=30, unique=True, verbose_name='Токен')),
                ('length', models.IntegerField(default=0, verbose_name='Длина реза, мм')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина, мм')),
                ('height', models.IntegerField(default=0, verbose_name='Высота, мм')),
                ('entries', models.IntegerField(default=0, verbose_name='Количество заходов')),
            ],
            options={
                'verbose_name': 'чертеж',
                'verbose_name_plural': 'чертежи',
            },
        ),
    ]
