# Generated by Django 4.0.5 on 2022-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeightLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Высота слоя')),
                ('koef', models.FloatField(default=0.0, verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'высота слоя',
                'verbose_name_plural': 'варианты высоты слоя',
            },
        ),
        migrations.CreateModel(
            name='TypePlastic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('density', models.FloatField(default=1.0, verbose_name='Плотность, гр/см3')),
                ('cost_coil', models.FloatField(default=0.0, verbose_name='Стоимость за катушку')),
                ('weight_coil', models.FloatField(default=0.0, verbose_name='Вес в катушке, кг')),
            ],
            options={
                'verbose_name': 'тип пластика',
                'verbose_name_plural': 'типы пластика',
            },
        ),
    ]
