# Generated by Django 4.1 on 2022-08-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='api.organization'),
        ),
    ]
