# Generated by Django 3.2.12 on 2022-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
    ]
